version: '3'

services:
  asport-server:
    build: .
    network_mode: host
    restart: always
    volumes:
      - ./cert:/cert
      - ./server.quick.example.toml:/server.quick.example.toml
    command: -c /server.quick.example.toml